ELK_EVENT_LIST = [
    'SWITCH_CONN_EVENT',
    'SWITCH_DISCONN_EVENT',
    'PORT_CONN_EVENT',
    'PORT_DISCONN_EVENT',
    'IP_DUP_EVENT',
    'TRAFFIC_OVERSUBSCRIPTION_EVENT',
    'TRAFFIC_DDOS_ATTACK_EVENT'
]

SWITCH_CONN_EVENT = 'SWITCH_CONN_EVENT'
SWITCH_DISCONN_EVENT = 'SWITCH_DISCONN_EVENT'
PORT_CONN_EVENT = 'PORT_CONN_EVENT'
PORT_DISCONN_EVENT = 'PORT_DISCONN_EVENT'
IP_DUP_EVENT = 'IP_DUP_EVENT'
TRAFFIC_OVERSUBSCRIPTION_EVENT = 'TRAFFIC_OVERSUBSCRIPTION_EVENT'
TRAFFIC_DDOS_ATTACK_EVENT = 'TRAFFIC_DDOS_ATTACK_EVENT'
